[build-system]
build-backend = "poetry.masonry.api"

[tool]

[tool.poetry]
authors = ["Navi Sai"]
description = "Mentor at MetaBronx"
name = "runner"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^1.1.1"
[tool.poetry.dev-dependencies]
